{
 "title": "Hospital System Monitoring",
 "tags": [ "fastapi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (method, handler)",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Error Rate (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx Errors"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx Errors"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) by (handler) / sum(rate(http_request_duration_seconds_count[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}